export type GlossaryCategory =
  | 'propagation'
  | 'channel-model'
  | 'multipath'
  | 'coherence'
  | 'statistical'
  | 'detection'
  | 'performance'
  | 'diversity'
  | 'info-theory'
  | 'capacity';

export interface GlossaryTerm {
  id: string;
  term: string;
  termKo: string;
  category: GlossaryCategory;
  definition: string;
  mathFormula?: string;
  href?: string;
}

export const categoryLabels: Record<GlossaryCategory, string> = {
  propagation: '전파/경로손실',
  'channel-model': '채널 모델',
  multipath: '다중경로',
  coherence: '코히런스',
  statistical: '통계 모델',
  detection: '검출·추정',
  performance: '성능 지표',
  diversity: '다이버시티',
  'info-theory': '정보이론',
  capacity: '채널 용량',
};

export const glossaryTerms: GlossaryTerm[] = [
  // ── propagation ──
  {
    id: 'free-space-path-loss',
    term: 'Free-Space Path Loss (FSPL)',
    termKo: '자유공간 경로손실',
    category: 'propagation',
    definition: '장애물 없이 직선 전파할 때 거리에 따른 전력 감쇠. 거리 2배 시 6 dB 손실.',
    mathFormula: String.raw`\text{FSPL} = \left(\frac{4\pi d}{\lambda}\right)^2`,
    href: '/tse/2#free-space-model',
  },
  {
    id: 'friis-formula',
    term: 'Friis Transmission Formula',
    termKo: '프리스 전송 공식',
    category: 'propagation',
    definition: '자유공간에서 송·수신 안테나 이득과 거리를 반영한 수신전력 공식.',
    mathFormula: String.raw`P_r = P_t G_t G_r \left(\frac{\lambda}{4\pi d}\right)^2`,
    href: '/tse/2#free-space-model',
  },
  {
    id: 'path-loss-exponent',
    term: 'Path Loss Exponent',
    termKo: '경로손실 지수',
    category: 'propagation',
    definition: '수신전력이 거리에 따라 감쇠하는 속도를 나타내는 지수 n. 자유공간 n=2, 도심 n=3~5.',
    mathFormula: String.raw`P_r \propto d^{-n}`,
    href: '/tse/2#shadowing-model',
  },
  {
    id: 'shadowing',
    term: 'Shadowing (Log-normal)',
    termKo: '섀도잉 (로그정규 페이딩)',
    category: 'propagation',
    definition: '건물·언덕 등 장애물에 의해 같은 거리에서도 수신전력이 달라지는 현상. dB 스케일에서 정규분포를 따름.',
    mathFormula: String.raw`X_{\sigma} \sim \mathcal{N}(0,\sigma^2),\quad \sigma \approx 6\text{–}12\;\text{dB}`,
    href: '/tse/2#shadowing-model',
  },
  {
    id: 'large-scale-fading',
    term: 'Large-Scale Fading',
    termKo: '대규모 페이딩',
    category: 'propagation',
    definition: '거리 및 지형에 따른 평균적 신호 감쇠. 경로손실과 섀도잉을 포함.',
    href: '/tse/2#intro',
  },
  {
    id: 'small-scale-fading',
    term: 'Small-Scale Fading',
    termKo: '소규모 페이딩',
    category: 'propagation',
    definition: '다중경로 간섭으로 파장 스케일(수 cm)에서 발생하는 빠른 전력 변동. 수십 dB의 deep fade 가능.',
    href: '/tse/2#intro',
  },
  {
    id: 'two-ray-model',
    term: 'Two-Ray Ground Reflection',
    termKo: '이선 지면반사 모델',
    category: 'propagation',
    definition: '직접파와 지면 반사파 두 경로만 고려하는 전파 모델. 근거리에서 간섭 패턴, 원거리에서 d⁻⁴ 감쇠.',
    href: '/tse/2#wall-reflection-model',
  },

  // ── channel-model ──
  {
    id: 'ltv-channel',
    term: 'Linear Time-Varying (LTV) Channel',
    termKo: '선형 시변 채널',
    category: 'channel-model',
    definition: '채널 특성이 시간에 따라 변하지만 입출력 관계는 선형인 채널. 무선 채널의 기본 모델.',
    mathFormula: String.raw`y(t) = \int h(t,\tau)\,x(t-\tau)\,d\tau`,
    href: '/tse/2#io-model',
  },
  {
    id: 'impulse-response',
    term: 'Channel Impulse Response',
    termKo: '채널 임펄스 응답',
    category: 'channel-model',
    definition: '임펄스 입력에 대한 채널 출력. 시간 t와 지연 τ의 함수로 채널을 완전히 기술.',
    mathFormula: String.raw`h(t,\tau) = \sum_k a_k(t)\,e^{j\phi_k(t)}\,\delta(\tau - \tau_k)`,
    href: '/tse/2#io-model',
  },
  {
    id: 'baseband-representation',
    term: 'Baseband Equivalent',
    termKo: '기저대역 등가 표현',
    category: 'channel-model',
    definition: '반송파 주파수를 제거하고 복소 포락선만 다루는 표현. 분석과 시뮬레이션을 단순화.',
    mathFormula: String.raw`y_b(t) = \int h_b(t,\tau)\,x_b(t-\tau)\,d\tau`,
    href: '/tse/2#io-model',
  },
  {
    id: 'discrete-time-model',
    term: 'Discrete-Time I/O Model',
    termKo: '이산시간 입출력 모델',
    category: 'channel-model',
    definition: '연속 채널을 샘플링하여 유한 개 탭으로 표현. 실제 디지털 수신기 설계의 출발점.',
    mathFormula: String.raw`y[n] = \sum_{\ell=0}^{L-1} h_\ell[n]\,x[n-\ell] + w[n]`,
    href: '/tse/2#io-model',
  },
  {
    id: 'awgn',
    term: 'AWGN (Additive White Gaussian Noise)',
    termKo: '가산 백색 가우시안 잡음',
    category: 'channel-model',
    definition: '모든 주파수에서 균일한 전력 스펙트럼을 가지며 가우시안 분포를 따르는 잡음.',
    mathFormula: String.raw`w[n] \sim \mathcal{CN}(0, N_0)`,
    href: '/tse/2#io-model',
  },
  {
    id: 'flat-fading',
    term: 'Flat Fading',
    termKo: '평탄 페이딩',
    category: 'channel-model',
    definition: '신호 대역폭이 코히런스 대역폭보다 좁아 모든 주파수 성분이 동일하게 페이딩되는 채널.',
    mathFormula: String.raw`W \ll W_c \implies y[n] = h[n]\,x[n] + w[n]`,
    href: '/tse/2#io-model',
  },
  {
    id: 'frequency-selective',
    term: 'Frequency-Selective Fading',
    termKo: '주파수 선택적 페이딩',
    category: 'channel-model',
    definition: '신호 대역폭이 코히런스 대역폭보다 넓어 주파수에 따라 다른 감쇠를 겪는 채널.',
    mathFormula: String.raw`W > W_c \implies L > 1 \text{ taps}`,
    href: '/tse/2#io-model',
  },

  // ── multipath ──
  {
    id: 'multipath',
    term: 'Multipath Propagation',
    termKo: '다중경로 전파',
    category: 'multipath',
    definition: '송신 신호가 반사·회절·산란을 통해 여러 경로로 수신기에 도달하는 현상.',
    href: '/tse/2#multipath',
  },
  {
    id: 'los',
    term: 'Line-of-Sight (LOS)',
    termKo: '가시선 경로',
    category: 'multipath',
    definition: '송·수신기 사이 장애물 없이 직선으로 연결되는 경로. 가장 강하고 안정적인 성분.',
    href: '/tse/2#multipath',
  },
  {
    id: 'nlos',
    term: 'Non-Line-of-Sight (NLOS)',
    termKo: '비가시선',
    category: 'multipath',
    definition: '직접 경로가 차단되어 반사·회절 경로만 존재하는 환경. Rayleigh 페이딩 모델 적용.',
    href: '/tse/2#multipath',
  },
  {
    id: 'reflection',
    term: 'Reflection',
    termKo: '반사',
    category: 'multipath',
    definition: '파장보다 훨씬 큰 평탄한 면(건물벽, 지면)에서 전파가 반사되는 현상.',
    href: '/tse/2#multipath',
  },
  {
    id: 'diffraction',
    term: 'Diffraction',
    termKo: '회절',
    category: 'multipath',
    definition: '건물 모서리나 언덕 같은 날카로운 경계에서 전파가 구부러져 NLOS 영역에 도달하는 현상.',
    href: '/tse/2#multipath',
  },
  {
    id: 'scattering',
    term: 'Scattering',
    termKo: '산란',
    category: 'multipath',
    definition: '파장 이하 크기의 물체(나뭇잎, 가로등)에 의해 전파가 여러 방향으로 흩어지는 현상.',
    href: '/tse/2#multipath',
  },
  {
    id: 'doppler-shift',
    term: 'Doppler Shift',
    termKo: '도플러 시프트',
    category: 'multipath',
    definition: '송·수신기의 상대 이동으로 수신 주파수가 변하는 현상. 접근 시 주파수 증가, 이탈 시 감소.',
    mathFormula: String.raw`f_D = \frac{v f_c}{c}\cos\theta`,
    href: '/tse/2#doppler',
  },
  {
    id: 'doppler-spread',
    term: 'Doppler Spread',
    termKo: '도플러 확산',
    category: 'multipath',
    definition: '다중경로의 도래각 차이로 발생하는 도플러 시프트의 최대 폭. 채널 시간 변화 속도를 결정.',
    mathFormula: String.raw`D_s = 2 f_D^{\max} = \frac{2v}{\lambda}`,
    href: '/tse/2#doppler',
  },
  {
    id: 'deep-fade',
    term: 'Deep Fade',
    termKo: '깊은 페이딩',
    category: 'multipath',
    definition: '다중경로 신호들이 상쇄 간섭하여 수신전력이 극도로 낮아지는 현상. 수십 dB 손실 가능.',
    href: '/tse/2#multipath',
  },
  {
    id: 'phasor',
    term: 'Phasor (Complex Vector)',
    termKo: '페이저 (복소 벡터)',
    category: 'multipath',
    definition: '진폭과 위상을 가진 복소수로, 다중경로 각 성분을 표현. 벡터 합이 수신 신호를 결정.',
    mathFormula: String.raw`h = \sum_k a_k e^{j\phi_k}`,
    href: '/tse/2#multipath',
  },

  // ── coherence ──
  {
    id: 'delay-spread',
    term: 'Delay Spread',
    termKo: '지연 확산',
    category: 'coherence',
    definition: '다중경로 도착 시간의 최대 차이. 심볼 간 간섭(ISI)의 원인.',
    mathFormula: String.raw`T_d = \tau_{\max} - \tau_{\min}`,
    href: '/tse/2#parameters',
  },
  {
    id: 'coherence-bandwidth',
    term: 'Coherence Bandwidth',
    termKo: '코히런스 대역폭',
    category: 'coherence',
    definition: '채널 주파수 응답이 거의 일정한 주파수 범위. 지연 확산의 역수에 비례.',
    mathFormula: String.raw`W_c \approx \frac{1}{T_d}`,
    href: '/tse/2#parameters',
  },
  {
    id: 'coherence-time',
    term: 'Coherence Time',
    termKo: '코히런스 시간',
    category: 'coherence',
    definition: '채널 계수가 거의 일정하게 유지되는 시간. 도플러 확산의 역수에 비례.',
    mathFormula: String.raw`T_c \approx \frac{1}{D_s}`,
    href: '/tse/2#parameters',
  },
  {
    id: 'underspread',
    term: 'Underspread Channel',
    termKo: '언더스프레드 채널',
    category: 'coherence',
    definition: '지연 확산과 도플러 확산의 곱이 1보다 훨씬 작은 채널. 실제 무선 채널의 일반적 특성.',
    mathFormula: String.raw`T_d \cdot D_s \ll 1`,
    href: '/tse/2#parameters',
  },
  {
    id: 'isi',
    term: 'Inter-Symbol Interference (ISI)',
    termKo: '심볼간 간섭',
    category: 'coherence',
    definition: '지연 확산이 심볼 주기보다 커서 인접 심볼이 겹치는 현상. 등화기 또는 OFDM으로 대응.',
    href: '/tse/2#parameters',
  },

  // ── statistical ──
  {
    id: 'rayleigh-fading',
    term: 'Rayleigh Fading',
    termKo: '레일리 페이딩',
    category: 'statistical',
    definition: 'NLOS 환경에서 많은 산란 경로가 합쳐질 때의 페이딩 모델. 진폭이 Rayleigh 분포를 따름.',
    mathFormula: String.raw`|h| \sim \text{Rayleigh}(\sigma),\quad h \sim \mathcal{CN}(0, 2\sigma^2)`,
    href: '/tse/2#statistical',
  },
  {
    id: 'rician-fading',
    term: 'Rician Fading',
    termKo: '라이시안 페이딩',
    category: 'statistical',
    definition: 'LOS 경로가 존재할 때의 페이딩 모델. K-factor가 클수록 LOS 성분 우세.',
    mathFormula: String.raw`K = \frac{|h_{\text{LOS}}|^2}{2\sigma^2}`,
    href: '/tse/2#statistical',
  },
  {
    id: 'k-factor',
    term: 'Rician K-Factor',
    termKo: 'K-인자',
    category: 'statistical',
    definition: 'LOS 성분과 산란 성분의 전력 비. K→0이면 Rayleigh, K→∞이면 AWGN에 수렴.',
    mathFormula: String.raw`K = \frac{\text{LOS power}}{\text{Scattered power}}`,
    href: '/tse/2#statistical',
  },
  {
    id: 'clarke-model',
    term: "Clarke's Model (Jakes)",
    termKo: '클라크 모델 (제이크스)',
    category: 'statistical',
    definition: '수평면에서 등방 산란을 가정한 도플러 스펙트럼 모델. U자형 스펙트럼이 특징.',
    mathFormula: String.raw`S(f) = \frac{1}{\pi f_D^{\max}\sqrt{1 - (f/f_D^{\max})^2}}`,
    href: '/tse/2#statistical',
  },
  {
    id: 'cn-distribution',
    term: 'Circularly-Symmetric Complex Gaussian',
    termKo: '원형 대칭 복소 가우시안',
    category: 'statistical',
    definition: '실수부와 허수부가 독립 동일 정규분포를 따르는 복소 확률변수. 다중경로 합의 극한 분포.',
    mathFormula: String.raw`h \sim \mathcal{CN}(\mu, \sigma^2)`,
    href: '/tse/2#statistical',
  },
  {
    id: 'clt',
    term: 'Central Limit Theorem',
    termKo: '중심극한정리',
    category: 'statistical',
    definition: '독립 확률변수의 합이 정규분포에 수렴하는 정리. 다중 산란경로 합의 Rayleigh 분포를 정당화.',
    href: '/tse/2#statistical',
  },

  // ── detection ──
  {
    id: 'gaussian-distribution',
    term: 'Gaussian Distribution',
    termKo: '가우시안 분포 (정규분포)',
    category: 'detection',
    definition: '평균과 분산으로 완전히 기술되는 연속 확률분포. 잡음 모델링의 기본.',
    mathFormula: String.raw`f(x) = \frac{1}{\sqrt{2\pi\sigma^2}}\exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)`,
    href: '/tse/2#appendix-a',
  },
  {
    id: 'ml-detection',
    term: 'Maximum Likelihood (ML) Detection',
    termKo: '최대우도 검출',
    category: 'detection',
    definition: '수신 신호의 관측 확률을 최대화하는 송신 심볼을 선택하는 최적 검출 기법.',
    mathFormula: String.raw`\hat{x} = \arg\max_{x \in \mathcal{X}} p(y \mid x)`,
    href: '/tse/2#appendix-a',
  },
  {
    id: 'map-detection',
    term: 'MAP (Maximum A Posteriori) Detection',
    termKo: 'MAP 검출',
    category: 'detection',
    definition: '사전확률까지 고려한 검출 기법. 사전확률이 균등하면 ML과 동일.',
    mathFormula: String.raw`\hat{x} = \arg\max_{x} p(x \mid y) = \arg\max_{x} p(y \mid x)\,p(x)`,
    href: '/tse/2#appendix-a',
  },
  {
    id: 'mmse-estimation',
    term: 'MMSE Estimation',
    termKo: '최소평균제곱오차 추정',
    category: 'detection',
    definition: '평균 제곱 오차를 최소화하는 추정. 가우시안 모델에서 조건부 평균과 동일.',
    mathFormula: String.raw`\hat{x}_{\text{MMSE}} = \mathbb{E}[x \mid y]`,
    href: '/tse/2#appendix-a',
  },
  {
    id: 'sufficient-statistic',
    term: 'Sufficient Statistic',
    termKo: '충분통계량',
    category: 'detection',
    definition: '원래 데이터의 모든 관련 정보를 보존하는 축약 통계량. 차원 축소를 가능하게 함.',
    href: '/tse/2#appendix-a',
  },
  {
    id: 'q-function',
    term: 'Q-Function',
    termKo: 'Q-함수',
    category: 'detection',
    definition: '표준정규분포의 꼬리 확률. 오류 확률 계산에 사용.',
    mathFormula: String.raw`Q(x) = \frac{1}{\sqrt{2\pi}}\int_x^{\infty} e^{-t^2/2}\,dt`,
    href: '/tse/2#appendix-a',
  },

  // ── performance ──
  {
    id: 'snr',
    term: 'SNR (Signal-to-Noise Ratio)',
    termKo: '신호 대 잡음비',
    category: 'performance',
    definition: '수신 신호 전력과 잡음 전력의 비. 통신 품질의 가장 기본적인 지표.',
    mathFormula: String.raw`\text{SNR} = \frac{P_{\text{signal}}}{P_{\text{noise}}}`,
    href: '/tse/2#main-plot',
  },
  {
    id: 'ber',
    term: 'BER (Bit Error Rate)',
    termKo: '비트 오류율',
    category: 'performance',
    definition: '전송된 비트 중 오류가 발생한 비트의 비율. 디지털 통신 성능의 핵심 척도.',
    href: '/tse/2#main-plot',
  },
  {
    id: 'outage-probability',
    term: 'Outage Probability',
    termKo: '아웃에이지 확률',
    category: 'performance',
    definition: '채널 상태가 목표 데이터율을 지원하지 못할 확률. 느린 페이딩 채널의 성능 지표.',
    mathFormula: String.raw`p_{\text{out}} = P(\log_2(1 + \text{SNR}\cdot|h|^2) < R)`,
    href: '/tse/2#main-plot',
  },
  {
    id: 'ergodic-capacity',
    term: 'Ergodic Capacity',
    termKo: '에르고딕 용량',
    category: 'performance',
    definition: '채널 상태의 시간 평균 용량. 빠른 페이딩에서 달성 가능한 최대 평균 전송률.',
    mathFormula: String.raw`C_{\text{erg}} = \mathbb{E}[\log_2(1 + \text{SNR}\cdot|h|^2)]`,
    href: '/tse/2#main-plot',
  },
  {
    id: 'diversity',
    term: 'Diversity',
    termKo: '다이버시티',
    category: 'performance',
    definition: '독립적 페이딩 경로를 다수 확보하여 deep fade 확률을 줄이는 기법. 시간/주파수/공간 다이버시티.',
    href: '/tse/2#main-plot',
  },
  {
    id: 'diversity-order',
    term: 'Diversity Order',
    termKo: '다이버시티 차수',
    category: 'performance',
    definition: '높은 SNR에서 오류 확률이 감소하는 기울기. L개 독립 경로 시 P_e ∝ SNR^(-L).',
    mathFormula: String.raw`d = -\lim_{\text{SNR}\to\infty}\frac{\log P_e}{\log \text{SNR}}`,
    href: '/tse/2#main-plot',
  },
  {
    id: 'channel-capacity',
    term: 'Channel Capacity',
    termKo: '채널 용량',
    category: 'performance',
    definition: '주어진 채널에서 오류 없이 전송 가능한 최대 데이터율. Shannon의 정보이론에서 정의.',
    mathFormula: String.raw`C = \log_2(1 + \text{SNR})`,
    href: '/tse/2#main-plot',
  },
  {
    id: 'ofdm',
    term: 'OFDM',
    termKo: '직교 주파수 분할 다중화',
    category: 'performance',
    definition: '광대역 채널을 다수의 좁은 부반송파로 분할하여 각각이 평탄 페이딩을 겪도록 하는 변조 방식.',
    href: '/tse/2#parameters',
  },

  // ── diversity (Chapter 3) ──
  {
    id: 'coherent-detection',
    term: 'Coherent Detection',
    termKo: '코히어런트 검출',
    category: 'diversity',
    definition: '채널 이득을 알고 있을 때, 수신 신호를 채널 보정 후 심볼 공간에서 최소 거리로 판정하는 검출 방식.',
    mathFormula: String.raw`\hat{x} = \arg\min_{x_i} |y - h x_i|^2`,
    href: '/tse/3#detection',
  },
  {
    id: 'noncoherent-detection',
    term: 'Noncoherent Detection',
    termKo: '비코히어런트 검출',
    category: 'diversity',
    definition: '채널 위상을 모를 때, 에너지(크기) 기반으로 판정하는 검출 방식. 구현이 단순하나 성능 열위.',
    href: '/tse/3#detection',
  },
  {
    id: 'time-diversity',
    term: 'Time Diversity',
    termKo: '시간 다이버시티',
    category: 'diversity',
    definition: '같은 정보를 시간적으로 분산시켜 독립 페이드를 경험하게 하는 기법. 인터리빙과 코딩으로 구현.',
    mathFormula: String.raw`L_{\text{time}} \approx D / T_c`,
    href: '/tse/3#time-diversity',
  },
  {
    id: 'antenna-diversity',
    term: 'Antenna (Space) Diversity',
    termKo: '안테나 (공간) 다이버시티',
    category: 'diversity',
    definition: '물리적으로 떨어진 안테나로 독립 페이드 가지를 확보하는 기법. 추가 지연 없이 다이버시티 확보.',
    href: '/tse/3#antenna-diversity',
  },
  {
    id: 'frequency-diversity-term',
    term: 'Frequency Diversity',
    termKo: '주파수 다이버시티',
    category: 'diversity',
    definition: '주파수 선택적 채널의 구조를 다이버시티 자원으로 활용하는 기법. OFDM 코딩/인터리빙으로 수확.',
    href: '/tse/3#frequency-diversity',
  },
  {
    id: 'mrc',
    term: 'Maximal Ratio Combining (MRC)',
    termKo: '최대비 결합',
    category: 'diversity',
    definition: '각 가지에 채널 이득의 켤레 복소수를 가중하여 결합하는 최적 다이버시티 결합 기법.',
    mathFormula: String.raw`z = \sum_{\ell} h_\ell^* y_\ell,\; \text{SNR}_{\text{out}} = \sum_{\ell} |h_\ell|^2 \cdot \text{SNR}`,
    href: '/tse/3#simo',
  },
  {
    id: 'alamouti-code',
    term: 'Alamouti Code',
    termKo: '알라무티 코드',
    category: 'diversity',
    definition: '2개 송신 안테나로 full transmit diversity를 얻는 직교 시공간 블록 코드.',
    mathFormula: String.raw`\mathbf{X} = \begin{bmatrix} x_1 & -x_2^* \\ x_2 & x_1^* \end{bmatrix}`,
    href: '/tse/3#alamouti',
  },
  {
    id: 'array-gain',
    term: 'Array Gain',
    termKo: '어레이 이득',
    category: 'diversity',
    definition: '다수 안테나 결합으로 평균 SNR이 안테나 수에 비례하여 증가하는 효과.',
    href: '/tse/3#simo',
  },
  {
    id: 'interleaving',
    term: 'Interleaving',
    termKo: '인터리빙',
    category: 'diversity',
    definition: '코드 심볼의 시간 순서를 섞어 각 심볼이 독립적인 페이딩을 경험하도록 하는 기법.',
    href: '/tse/3#interleaving',
  },
  {
    id: 'csi',
    term: 'Channel State Information (CSI)',
    termKo: '채널 상태 정보',
    category: 'diversity',
    definition: '수신기가 보유한 채널 이득 정보. 정확할수록 코히어런트 검출 성능이 향상됨.',
    href: '/tse/3#channel-uncertainty',
  },
  {
    id: 'effective-snr',
    term: 'Effective SNR',
    termKo: '유효 SNR',
    category: 'diversity',
    definition: '채널 추정 오차를 반영한 실질적 SNR. 추정 오차가 크면 nominal SNR과 크게 괴리됨.',
    mathFormula: String.raw`\gamma_{\text{eff}} = \frac{\gamma_d}{1 + \gamma_d \sigma_e^2}`,
    href: '/tse/3#effective-snr',
  },
  {
    id: 'pilot',
    term: 'Pilot Symbol',
    termKo: '파일럿 심볼',
    category: 'diversity',
    definition: '채널 추정을 위해 송수신기가 미리 약속한 알려진 심볼. 데이터 전송 자원과 트레이드오프 관계.',
    href: '/tse/3#pilot-estimation',
  },
  {
    id: 'simo',
    term: 'SIMO (Single-Input Multiple-Output)',
    termKo: 'SIMO',
    category: 'diversity',
    definition: '송신 1개, 수신 다수 안테나 구성. MRC 결합으로 array gain과 diversity gain을 동시에 확보.',
    href: '/tse/3#simo',
  },
  {
    id: 'miso',
    term: 'MISO (Multiple-Input Single-Output)',
    termKo: 'MISO',
    category: 'diversity',
    definition: '송신 다수, 수신 1개 안테나 구성. Alamouti 코드 등 송신 다이버시티 기법으로 구현.',
    href: '/tse/3#alamouti',
  },

  // ── info-theory (Appendix B) ──
  {
    id: 'dmc',
    term: 'Discrete Memoryless Channel (DMC)',
    termKo: '이산 무기억 채널',
    category: 'info-theory',
    definition: '각 채널 사용이 독립인 가장 기본적인 채널 추상화. 전이확률 p(y|x)로 완전히 규정.',
    mathFormula: String.raw`p(y^n|x^n) = \prod_{i=1}^{n} p(y_i|x_i)`,
    href: '/tse/3#appendix-b1',
  },
  {
    id: 'entropy',
    term: 'Entropy',
    termKo: '엔트로피',
    category: 'info-theory',
    definition: '확률변수의 불확실성(정보량)을 비트 단위로 측정하는 지표.',
    mathFormula: String.raw`H(X) = -\sum_x p(x) \log_2 p(x)`,
    href: '/tse/3#appendix-b2',
  },
  {
    id: 'mutual-information',
    term: 'Mutual Information',
    termKo: '상호정보량',
    category: 'info-theory',
    definition: '한 확률변수의 관측이 다른 확률변수에 대해 줄여주는 불확실성의 평균량.',
    mathFormula: String.raw`I(X;Y) = H(X) - H(X|Y) = H(Y) - H(Y|X)`,
    href: '/tse/3#appendix-b2',
  },
  {
    id: 'coding-theorem',
    term: 'Noisy Channel Coding Theorem',
    termKo: '잡음 채널 코딩 정리',
    category: 'info-theory',
    definition: 'R < C이면 오류율을 임의로 줄일 수 있고, R > C이면 불가능하다는 Shannon의 기본 정리.',
    href: '/tse/3#appendix-b3',
  },
  {
    id: 'awgn-capacity',
    term: 'AWGN Capacity',
    termKo: 'AWGN 용량',
    category: 'info-theory',
    definition: '가산 백색 가우시안 잡음 채널의 용량. 전력-대역폭 트레이드오프의 기본 공식.',
    mathFormula: String.raw`C = W \log_2\!\left(1 + \frac{P}{N_0 W}\right)`,
    href: '/tse/3#appendix-b4',
  },
  {
    id: 'waterfilling',
    term: 'Waterfilling',
    termKo: '워터필링',
    category: 'info-theory',
    definition: '병렬 부채널에서 용량을 최대화하는 최적 전력 배분 방법. SNR이 높은 채널에 더 많은 전력 배정.',
    href: '/tse/3#appendix-b4',
  },
  {
    id: 'sphere-packing',
    term: 'Sphere Packing Bound',
    termKo: '구면 패킹 한계',
    category: 'info-theory',
    definition: '코딩 문제를 고차원 기하학으로 해석. 잡음 구 겹침 없이 배치 가능한 코드워드 수의 상한.',
    mathFormula: String.raw`M \lesssim \left(1 + \frac{P}{N_0}\right)^{n/2}`,
    href: '/tse/3#appendix-b5',
  },
  {
    id: 'binary-entropy',
    term: 'Binary Entropy Function',
    termKo: '이진 엔트로피 함수',
    category: 'info-theory',
    definition: '이진 확률변수의 엔트로피. BSC/BEC 용량 계산에서 핵심 역할.',
    mathFormula: String.raw`h_2(p) = -p\log_2 p - (1-p)\log_2(1-p)`,
    href: '/tse/3#appendix-b2',
  },
  {
    id: 'data-processing',
    term: 'Data Processing Inequality',
    termKo: '데이터 처리 부등식',
    category: 'info-theory',
    definition: '후처리는 새로운 정보를 만들지 못한다는 정보이론의 기본 부등식.',
    mathFormula: String.raw`X \to Y \to Z \;\Rightarrow\; I(X;Z) \le I(X;Y)`,
    href: '/tse/3#appendix-b2',
  },

  // ── capacity (Chapter 5) ──
  {
    id: 'channel-capacity-ch5',
    term: 'Channel Capacity',
    termKo: '채널 용량',
    category: 'capacity',
    definition: '주어진 채널에서 입력 분포를 최적화했을 때 달성 가능한 최대 상호정보량. 오류 없는 전송의 궁극적 한계.',
    mathFormula: String.raw`C = \max_{p(x)} I(X;Y)`,
    href: '/tse/5#5.1',
  },
  {
    id: 'shannon-capacity',
    term: 'Shannon Capacity',
    termKo: '섀넌 용량',
    category: 'capacity',
    definition: 'AWGN 채널에서 대역폭 W와 SNR로 표현되는 용량 공식. 전력과 대역폭의 트레이드오프를 정량화.',
    mathFormula: String.raw`C = W \log_2(1 + \text{SNR})`,
    href: '/tse/5#5.1',
  },
  {
    id: 'spectral-efficiency',
    term: 'Spectral Efficiency',
    termKo: '스펙트럼 효율',
    category: 'capacity',
    definition: '단위 대역폭당 달성 가능한 전송률. 대역폭 자원의 효율적 사용 정도를 나타내는 지표.',
    mathFormula: String.raw`\frac{C}{W} \;\text{[bits/s/Hz]}`,
    href: '/tse/5#5.1',
  },
  {
    id: 'power-limited-regime',
    term: 'Power-limited Regime',
    termKo: '전력 제한 영역',
    category: 'capacity',
    definition: '대역폭이 충분하고 전력이 부족한 영역. 용량이 전력에 선형 비례하며, 대역폭 증가 효과가 미미.',
    mathFormula: String.raw`C \approx \frac{P}{N_0 \ln 2}`,
    href: '/tse/5#5.2',
  },
  {
    id: 'bandwidth-limited-regime',
    term: 'Bandwidth-limited Regime',
    termKo: '대역폭 제한 영역',
    category: 'capacity',
    definition: '전력이 충분하고 대역폭이 부족한 영역. 용량이 대역폭에 로그 비례하며, 전력 증가 효과가 감소.',
    mathFormula: String.raw`C \approx W \log_2(\text{SNR})`,
    href: '/tse/5#5.2',
  },
  {
    id: 'waterfilling-capacity',
    term: 'Waterfilling',
    termKo: '워터필링',
    category: 'capacity',
    definition: '병렬 채널에서 용량을 최대화하는 최적 전력 배분. 잡음이 적은 부채널에 더 많은 전력을 할당.',
    mathFormula: String.raw`P_i = \left(\mu - \frac{N_0}{|h_i|^2}\right)^+`,
    href: '/tse/5#5.3',
  },
  {
    id: 'parallel-channel',
    term: 'Parallel Channel',
    termKo: '병렬 채널',
    category: 'capacity',
    definition: '독립적인 부채널의 집합으로 모델링되는 채널. 전체 용량은 각 부채널 용량의 합.',
    mathFormula: String.raw`C = \sum_i C_i`,
    href: '/tse/5#5.3',
  },
  {
    id: 'outage-capacity',
    term: 'Outage Capacity',
    termKo: '아웃에이지 용량',
    category: 'capacity',
    definition: '느린 페이딩 채널에서 일정 아웃에이지 확률 ε을 허용할 때 달성 가능한 최대 전송률.',
    mathFormula: String.raw`P(C < R) = \varepsilon`,
    href: '/tse/5#5.4',
  },
  {
    id: 'ergodic-capacity-ch5',
    term: 'Ergodic Capacity',
    termKo: '에르고딕 용량',
    category: 'capacity',
    definition: '빠른 페이딩 채널에서 채널 변동에 대한 평균 용량. 코드워드가 충분히 길어 모든 페이딩 상태를 경험.',
    mathFormula: String.raw`C_{\text{erg}} = \mathbb{E}[\log(1 + \text{SNR}\,|h|^2)]`,
    href: '/tse/5#5.4',
  },
  {
    id: 'channel-inversion',
    term: 'Channel Inversion',
    termKo: '채널 반전',
    category: 'capacity',
    definition: '채널 이득에 반비례하여 송신 전력을 조절하는 방식. 수신기에서 일정한 SNR을 유지하지만 전력 효율이 낮음.',
    mathFormula: String.raw`P(h) = \frac{\mu}{|h|^2}`,
    href: '/tse/5#5.4',
  },
  {
    id: 'outage-probability-ch5',
    term: 'Outage Probability',
    termKo: '아웃에이지 확률',
    category: 'capacity',
    definition: '순시 채널 용량이 목표 전송률 R을 지원하지 못할 확률. 느린 페이딩 채널의 핵심 성능 지표.',
    mathFormula: String.raw`P_{\text{out}} = P(C < R)`,
    href: '/tse/5#5.4',
  },
  {
    id: 'diversity-multiplexing-tradeoff',
    term: 'Diversity-Multiplexing Tradeoff',
    termKo: '다이버시티-멀티플렉싱 트레이드오프',
    category: 'capacity',
    definition: 'MIMO 시스템에서 다이버시티 이득과 공간 멀티플렉싱 이득 간의 근본적 트레이드오프 관계.',
    mathFormula: String.raw`d(r) = (M - r)(N - r)`,
    href: '/tse/5#5.4',
  },
];
